env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
  allowImportExportEverywhere: true
extends: airbnb-base
plugins:
 - import
rules: 
no-console: 0
import/extensions: "off"
no-underscore-dangle: [2, {"allow": ["__filename", "__dirname"] }]
